export  const homes = [
  {
    id: 1,
    name: 'Beautiful Family House',
    country: 'USA',
    rooms: 5,
    size: 450,
    price: 1_200_000,
  },
  {
    id: 2,
    name: 'Beautiful Family House',
    country: 'Canada',
    rooms: 6,
    size: 250,
    price: 2_750_000,
  },
  {
    id: 3,
    name: 'Beautiful Family House',
    country: 'UK',
    rooms: 4,
    size: 480,
    price: 850_000,
  },
  {
    id: 4,
    name: 'Beautiful Family House',
    country: 'Portugal',
    rooms: 6,
    size: 4230,
    price: 1_950_000,
  },
  {
    id: 5,
    name: 'Beautiful Family House',
    country: 'Germany',
    rooms: 18,
    size: 180,
    price: 9_500_000,
  },
  {
    id: 6,
    name: 'Beautiful Family House',
    country: 'Italy',
    rooms: 3,
    size: 325,
    price: 600_000,
  },
];